### PR TITLE
Implement gameplay audio

### PR DESCRIPTION
**Pull request by LumpBloom7**
This PR add sounds that are present during gameplay

This includes
* Pellet chomp
* Ghost eaten
* Bonus eaten
* Ghost siren loop (+2 elroy variants)
* Afraid loop
* Dead loop

### CODE REVIEW

**Comment by siew24** [comment]
CodeFactor failed😂😂

**Comment by LumpBloom7** [comment]
> CodeFactor failed😂😂

Don't mind it, just a nitpick to keep functions small.

**Comment by LumpBloom7** [comment]
@siew24
This should be ready to merge, since after (my) internal reviews, no one complained.
Any objections from your side?

**Comment by siew24** [comment]
No, not at all  😂

**Pull request merged**
