### PR TITLE
General gameplay improvements

### PR DESCRIPTION
**Pull request by LumpBloom7**

### CODE REVIEW

**Comment by LumpBloom7** [comment]
@siew24 Do you know how long the ghosts should stay in the house after being eaten? I can't really find info on that.

**Comment by siew24** [comment]
It's not because of time, it's because of the number of pellets eaten by
Pac

**Comment by LumpBloom7** [comment]
Any specific number? Do note this is the time they stay in after being eaten.



________________________________

**Comment by siew24** [comment]
And also the time also should be minimum after being eaten

**Comment by LumpBloom7** [comment]
What is the minimum?

**Comment by siew24** [comment]
Assume it comes out immediately 😅

**Pull request merged**
