### PR TITLE
Transition to using BloomFramework submodule + Solution improvements

### PR DESCRIPTION
**Pull request by LumpBloom7**
This PR replaces our provided BloomFramework code with a submodule to an unofficial branch of it.

Changes:
* Use submodule for BloomFramework. It is linked to an unofficial branch for now.
* Fast-forwards BloomFramework to a commit that supports SpriteText.
* Renamed solution "Test Bench" to "Pacman".
* Tidy up Pacman project filters.
* Various changes to Pacman project file to use the submodule properly.

### CODE REVIEW

**Comment by LumpBloom7** [comment]
@siew24
We now welcome SpriteText into our toolbox!!🎉🎉

**Comment by siew24** [comment]
There's some error about multiple conflicting objects...

**Comment by siew24** [comment]
> There's some error about multiple conflicting objects...

One is from KeyboardEvents and the other three are from the level object.

**Comment by LumpBloom7** [comment]
Build error? Shouldn't be...
After all the build pipeline is able to succeed.

Maybe a screenshot?

**Comment by siew24** [comment]
My bad :)

**Pull request merged**
